# Windows 环境数据源配置示例
# 适用于 Windows 本地开发环境

datasource:
  datasources:
    # MySQL 主数据源 (XAMPP/WAMP)
    mysql_primary:
      url: jdbc:mysql://localhost:3306/your_database?connectTimeout=10000&socketTimeout=10000&useUnicode=true&characterEncoding=UTF-8&useTimezone=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
      username: root
      password: ''  # XAMPP 默认无密码，请根据实际情况修改
      default: true
      hikari:
        pool-name: MySQLHikariCP
        maximum-pool-size: 10
        minimum-idle: 5

    # PostgreSQL 数据源 (本地安装)
    postgres_secondary:
      url: jdbc:postgresql://localhost:5432/your_postgres_db?connectTimeout=10&socketTimeout=10&useUnicode=true&characterEncoding=UTF-8
      username: postgres
      password: your_postgres_password  # 请替换为实际密码
      hikari:
        pool-name: PostgreSQLHikariCP
        maximum-pool-size: 8
        minimum-idle: 3

    # SQL Server 数据源 (SQL Server Express)
    sqlserver_db:
      url: jdbc:sqlserver://localhost:1433;databaseName=your_sqlserver_db;trustServerCertificate=true
      username: sa
      password: your_sqlserver_password  # 请替换为实际密码
      hikari:
        pool-name: SQLServerHikariCP
        maximum-pool-size: 6
        minimum-idle: 2

    # H2 内存数据库 (测试用)
    h2_test:
      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: ''
      hikari:
        pool-name: H2HikariCP
        maximum-pool-size: 5
        minimum-idle: 1

# 注意事项：
# 1. 请将 'your_database', 'your_postgres_db', 'your_sqlserver_db' 替换为实际的数据库名
# 2. 请将密码替换为实际的数据库密码
# 3. 确保对应的数据库服务已启动
# 4. 如果使用 XAMPP，MySQL 默认端口是 3306，无密码
# 5. 如果使用 PostgreSQL，默认端口是 5432
# 6. 如果使用 SQL Server Express，默认端口是 1433
